const fs = require('fs');
const path = require('path');

console.log('🔧 Setting up WhatsApp Mass Reporter Bot...');

// Check if .env exists
if (!fs.existsSync('.env')) {
    console.log('📝 Creating .env file...');
    const envTemplate = `# Telegram Configuration
TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
ADMIN_USER_ID=your_user_id_here

# WhatsApp Support Emails
WHATSAPP_SUPPORT_EMAIL=support@support.whatsapp.com
WHATSAPP_ABUSE_EMAIL=abuse@whatsapp.com

# Reporting Limits
MIN_REPORTS_PER_SESSION=10
MAX_REPORTS_PER_SESSION=100
MAX_REPORTS_PER_HOUR=200

# Email Configuration
EMAIL_SEND_DELAY=2000
MAX_EMAIL_ATTEMPTS=3
EMAIL_RETRY_DELAY=5000

# SMTP Configuration
SMTP_ENABLED=true
SMTP_SERVICE=gmail
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE=false
SMTP_EMAIL=your_email@gmail.com
SMTP_PASSWORD=your_app_password

# Email Headers
EMAIL_PRIORITY=high
EMAIL_IMPORTANCE=high
EMAIL_X_MAILER=WhatsApp Mass Reporter Bot v2.0`;
    
    fs.writeFileSync('.env', envTemplate);
    console.log('✅ .env file created. Please edit it with your credentials.');
}

// Check if templates directory exists
const templatesDir = path.join(__dirname, 'templates');
if (!fs.existsSync(templatesDir)) {
    console.log('📁 Creating templates directory...');
    fs.mkdirSync(templatesDir, { recursive: true });
}

// Check if report template exists
const templatePath = path.join(templatesDir, 'report-template.txt');
if (!fs.existsSync(templatePath)) {
    console.log('📄 Creating report template...');
    const templateContent = `URGENT: WhatsApp Terms of Service Violation Report

Report Reference: WRB-{timestamp}
Date: {date}
Time: {timestamp}

REPORTED WHATSAPP NUMBER:
Phone Number: {number}
Country Code: {countryCode}

VIOLATION CATEGORY:
{category}

INCIDENT DETAILS:
{description}

REQUESTED ACTION:
- Immediate investigation
- Account review and possible suspension

COMPLIANCE NOTES:
This report is submitted in good faith based on observed violations.

---
Generated by CodeX WhatsApp Reporter Bot`;
    
    fs.writeFileSync(templatePath, templateContent);
    console.log('✅ Report template created.');
}

console.log('✅ Setup complete!');
console.log('💡 Next steps:');
console.log('   1. Edit .env file with your credentials');
console.log('   2. Run: npm start');
console.log('   3. Message your bot on Telegram with /start');
